# Generated by Django 4.2.5 on 2023-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0018_alter_user_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DPI',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
