# Generated by Django 4.2.5 on 2023-10-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0019_alter_user_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto_perfil',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
