# Generated by Django 4.2.5 on 2023-10-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0023_alter_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Foto_perfil',
            field=models.ImageField(default='profile_default.png', null=True, upload_to='users/'),
        ),
    ]
