# Generated by Django 4.2.5 on 2023-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0025_alter_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usernamee',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Foto_perfil',
            field=models.ImageField(default='profile_default.png', null=True, upload_to='users/'),
        ),
    ]
