# Generated by Django 4.2.5 on 2023-10-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0026_user_usernamee_alter_user_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usernamee',
        ),
        migrations.AddField(
            model_name='user',
            name='Nombre_de_usuario',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
