# Generated by Django 4.2.5 on 2023-10-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0027_remove_user_usernamee_user_nombre_de_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Nombre_de_usuario',
        ),
    ]
